# Generated by Django 3.2.13 on 2022-04-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220430_1143'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peopleinfo',
            table='PeopleInfo',
        ),
    ]
